name: Pull Request Validation

# Pipeline executada quando um Pull Request for aberto ou atualizado com destino √† branch "develop".
on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Initial
        run: |
          echo "---------------------------------------------"
          echo "üöÄ Iniciando processo de valida√ß√£o do pull request com destino √† develop..."
          echo "Data e hora de in√≠cio: $(date +"%d/%m/%Y √†s %Hh%Mmin%Ss")"
          echo "---------------------------------------------"

      # baixa o c√≥digo do reposit√≥rio
      - name: Checkout repository
        uses: actions/checkout@v4

      # configura o Node.js (vers√£o 18)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # instala as depend√™ncias
      - name: Install dependencies
        run: npm ci

      # verifica se o c√≥digo segue os padr√µes
      - name: Lint check
        run: npm run lint

      # faz o build do projeto, garantindo que compila sem erros
      - name: Build test
        run: npm run build

      # checando conex√£o com o backend (API)
      - name: Check backend connection
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          echo "Checking backend availability at $VITE_API_URL"
          curl -f "$VITE_API_URL" || (echo "‚ùå API n√£o dispon√≠vel" && exit 1)

      - name: Validation Summary
        if: success()
        run: |
          echo "---------------------------------------------"
          echo "‚úÖ Pull Request validado com sucesso!"
          echo "Branch: develop"
          echo "Data e hora: $(date +"%d/%m/%Y √†s %Hh%Mmin%Ss")"
          echo "üöÄ Pronto para merge na main!"
          echo "---------------------------------------------"

      # resumo final de erro
      - name: Error handler
        if: failure()
        run: |
          echo "---------------------------------------------"
          echo "‚ùå Falha na valida√ß√£o do Pull Request!"
          echo "Branch: develop"
          echo "Data e hora: $(date +"%d/%m/%Y √†s %Hh%Mmin%Ss")"
          echo "---------------------------------------------"
